INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (1, 'Juan Carlos', 'Vivas Martinez', 'juanc.vivasm@gmail.com', '2023-01-26', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (2, 'Wilmarys', 'Navas Garcia', 'wilmarysnavas@gmail.com', '2023-01-26', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (3, 'Juan David', 'Vivas Navas', 'juand.vivasn@gmail.com', '2023-01-26', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (4, 'Cliente 04', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (5, 'Cliente 05', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (6, 'Cliente 06', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (7, 'Cliente 07', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (8, 'Cliente 08', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (9, 'Cliente 09', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (10, 'Cliente 10', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (11, 'Cliente 11', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (12, 'Cliente 12', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (13, 'Cliente 13', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (14, 'Cliente 14', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (15, 'Cliente 15', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (16, 'Cliente 16', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (17, 'Cliente 17', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (18, 'Cliente 18', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (19, 'Cliente 19', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (20, 'Cliente 20', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (21, 'Cliente 21', 'Doe', 'jhondoe@gmail.com', '2023-01-30', '');
